import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {appConfig} from "@/lib/config/app-config";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const {analytics, metadata: metadataConfig, siteUrl} = appConfig;

export const metadata: Metadata = {
  metadataBase: siteUrl ? new URL(siteUrl) : undefined,
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: metadataConfig.iconPath,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <head>
        {analytics.umami.enabled && analytics.umami.scriptSrc && analytics.umami.websiteId ? (
          <script
            defer
            src={analytics.umami.scriptSrc}
            data-website-id={analytics.umami.websiteId}
          />
        ) : null}
      </head>
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
